catalog/urls.py
from django.urls import path
from . import views
from django.db import models

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('rooms/', views.RoomListView.as_view(), name='rooms'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('authors/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('rooms/<int:pk>', views.RoomDetailView.as_view(), name='room-detail'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),	
    path('book/<uuid:pk>/borrow/', views.borrow_book, name='borrow_book'),
    path('book/<uuid:pk>/borrowfaculty/', views.borrow_book_faculty, name='borrow_book_faculty'),
    path('rooms/<uuid:pk>/borrow/', views.borrow_room, name='borrow_room'),
]

urlpatterns += [   
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
]

catalog/models.py
from django.db import models
from django.urls import reverse # Used to generate URLs by reversing the URL patterns
from django.contrib.auth.models import User, Group
import uuid # Required for unique book instances
from datetime import date
from catalog.choices import *
from django.contrib.auth.models import AbstractUser
import datetime

class Genre(models.Model):
    """Model representing a book genre."""
    name = models.CharField(max_length=200, help_text='Enter a book genre (e.g. Science Fiction)')
    
    def __str__(self):
        """String for representing the Model object."""
        return self.name

class Room(models.Model):
    
    name = models.CharField(max_length=200);

    description = models.CharField(max_length=200);
    
    def __str__(self):
        """String for representing the Model object."""
        return self.name
    
    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('room-detail', args=[str(self.id)])
    
class RoomInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    room = models.ForeignKey('Room', on_delete=models.SET_NULL, null=True)
    room_code = models.CharField(max_length=10)
    LOAN_STATUS = (
        ('a', 'Available'),
        ('r', 'Reserved'),
    )
    due_back = models.DateField(null=True, blank=True)
    
    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )
    
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    
    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set room as returned"),) 

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.room.name})'
    
    
class Book(models.Model):
    
    title = models.CharField(max_length=200)


    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
 
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')
    
    LOCATION_DEWEY = (
        ('000-099', 'Generalities'),
        ('100-199', 'Philosophy'),
        ('200-299', 'Religion'),
        ('300-399', 'Social Science'),
        ('400-499', 'Language'),
        ('500-599', 'Science & Math'),
        ('600-699', 'Technology'),
        ('700-799', 'The Arts'),
        ('800-899', 'Literature'),
        ('900-999', 'Geography & History'),
    )
    
    location = models.CharField(
        max_length = 7,
        choices = LOCATION_DEWEY,
        blank=True,
        help_text='Book Location'
    )
    
    tags = models.CharField(max_length=10,help_text='Tags',default='Tag')
    
    def __str__(self):
        """String for representing the Model object."""
        return self.title
    
    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ', '.join(genre.name for genre in self.genre.all()[:3])
    
    display_genre.short_description = 'Genre'

class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True) 
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    
    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
             return True
        return False

    LOAN_STATUS = (
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),) 

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'
    

class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']
    
    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'

class Language(models.Model):
    """Model representing a Language (e.g. English, French, Japanese, etc.)"""
    name = models.CharField(max_length=200,
                            help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)")

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.first_name

class Profile(models.Model):
    
    User.first_name = models.OneToOneField(User, on_delete=models.CASCADE)
    User.last_name = models.OneToOneField(User, on_delete=models.CASCADE)
    User.username = models.OneToOneField(User, on_delete=models.CASCADE)
    User.email = models.OneToOneField(User, on_delete=models.CASCADE)
    birth_date = models.DateField(null=True, blank=True)
    secretAnswer = models.CharField(max_length=100)   
    

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ author.first_name }}</h1>

 
  
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Author List</h1>
  {% if author_list %}
  <ul>
    {% for author in author_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author.first_name }} {{ author.last_name }}</a> 
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no authors in the library.</p>
  {% endif %}       
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p> 
  <p><strong>Location:</strong> {{ book.location }}</p>
  <p><strong>Publisher:</strong> {{ book.publisher }}</p>
  <p><strong>Year of Publicaton:</strong> {{ book.year }}</p>
  <p><strong>Language:</strong> {{ book.language }}</p>
  <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>  
  <p><strong>Tags:</strong>{% for genre in book.tags.all %} {{ tags }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>  

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    

    {% for copy in book.bookinstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
        
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{copy.due_back}}</p>
      {% endif %}
      
      <p><strong>Imprint:</strong> {{copy.imprint}}</p>
      <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>

       
       {% if copy.status == 'a' %}
        {% if usergroup.groups == "Faculty" %}
        <form method="POST" action ="{% url 'borrow_book_faculty' copy.id%}" enctype="multipart/form data">

         {% csrf_token %}
          <button type="submit" class="btn btn-success">Borrow the book</button>
        </form>
        {% endif %}
       {% endif %}
      
    
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Book List</h1>
  {% if book_list %}
  <ul>
    {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %}       
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})        
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/model_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Model list</h1>
    {% if copy_list %}
    <ul>
      {% for copy in copy_list %}
        <li>
          <a href="{{ copy.get_absolute_url }}">{{ model.model_number }}</a>
        </li>
      {% endfor %}
    </ul>
    {% else %}
        <p>There is no equipment in the database</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/room_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Name: {{ room.name }}</h1>

  <p><strong>Description:</strong> <a href="">{{ room.description }}</a></p> <!-- author detail link not yet defined -->
  

  <div style="margin-left:20px;margin-top:20px">
    <h4>Status</h4>

    {% for copy in room.roominstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
      <p class="text-muted"><strong>Room Code:</strong> {{copy.room_code}}</p>
      {% if copy.status != 'a' %}
        <p><strong>Reserved By:</strong> {{copy.borrower}}</p>
        <p><strong>Due to be returned:</strong> {{copy.due_back}}</p>
      {% endif %}
      
       {% if copy.status == 'a' %}
        <form method="POST" action ="{% url 'borrow_room' copy.id%}" enctype="multipart/form data">

         {% csrf_token %}
          <button type="submit" class="btn btn-success">Reserve Room</button>
        </form> {% endif %}
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/room_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Room List</h1>
  {% if room_list %}
  <ul>
    {% for room in room_list %}
      <li>
        <a href="{{ room.get_absolute_url }}">{{ room.name }}</a> ({{room.description }})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no rooms in the library.</p>
  {% endif %}       
{% endblock %}